// Auto-generated from 4x4 dati f.xlsx — Copy app sheet
// Columns: B=Fonti frammentate, C=Raccolta manuale, D=Regole incoerenti, E=Audit lento
// H=Diagnosi, I=Copy app, J=Fit Envizi, K=Raccomandazione Envizi

export interface MatrixEntry {
  diagnosi: string;
  copyApp: string;
  fitEnvizi: string;
  raccomandazione: string;
}

type Rating = "alto" | "medio" | "basso";
type Key = `${Rating}_${Rating}_${Rating}_${Rating}`;

const MATRIX: Record<Key, MatrixEntry> = {
  "alto_alto_alto_alto": { diagnosi: "fragilità sistemica del modello ESG", copyApp: "Il quadro indica fragilità sistemica del modello ESG: dati, processi, regole e controlli si amplificano negativamente e possono compromettere insieme affidabilità, velocità e capacità di rendicontazione. L'esposizione è critica; serve un esame immediato e completo della piattaforma ESG su fonti e integrazioni, workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_alto_alto_medio": { diagnosi: "fabbrica del dato difficile da governare", copyApp: "Il quadro indica fabbrica del dato difficile da governare: fonti disperse, passaggi umani e criteri variabili possono produrre un consolidato formalmente completo ma sostanzialmente instabile. Aggravanti: verifiche tardive. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_alto_alto_basso": { diagnosi: "fabbrica del dato difficile da governare", copyApp: "Il quadro indica fabbrica del dato difficile da governare: fonti disperse, passaggi umani e criteri variabili possono produrre un consolidato formalmente completo ma sostanzialmente instabile. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_alto_medio_alto": { diagnosi: "modello operativo opaco", copyApp: "Il quadro indica modello operativo opaco: il dato attraversa fonti e passaggi manuali senza una tracciabilità abbastanza rapida da sostenere verifiche e correzioni. Aggravanti: comparabilità instabile. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, workflow e automazioni, lineage e controlli e regole e perimetri di calcolo.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_alto_medio_medio": { diagnosi: "catena di raccolta frammentata e non scalabile", copyApp: "Il quadro indica catena di raccolta frammentata e non scalabile: la complessità cresce più rapidamente della capacità di acquisire e consolidare i dati in modo affidabile. Aggravanti: comparabilità instabile e verifiche tardive. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_alto_medio_basso": { diagnosi: "catena di raccolta frammentata e non scalabile", copyApp: "Il quadro indica catena di raccolta frammentata e non scalabile: la complessità cresce più rapidamente della capacità di acquisire e consolidare i dati in modo affidabile. Aggravanti: comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_alto_basso_alto": { diagnosi: "modello operativo opaco", copyApp: "Il quadro indica modello operativo opaco: il dato attraversa fonti e passaggi manuali senza una tracciabilità abbastanza rapida da sostenere verifiche e correzioni. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, workflow e automazioni e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_alto_basso_medio": { diagnosi: "catena di raccolta frammentata e non scalabile", copyApp: "Il quadro indica catena di raccolta frammentata e non scalabile: la complessità cresce più rapidamente della capacità di acquisire e consolidare i dati in modo affidabile. Aggravanti: verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, workflow e automazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_alto_basso_basso": { diagnosi: "catena di raccolta frammentata e non scalabile", copyApp: "Il quadro indica catena di raccolta frammentata e non scalabile: la complessità cresce più rapidamente della capacità di acquisire e consolidare i dati in modo affidabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni e workflow e automazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_medio_alto_alto": { diagnosi: "fondazione del reporting non difendibile", copyApp: "Il quadro indica fondazione del reporting non difendibile: la combinazione di fonti disperse, criteri variabili e prove tardive indebolisce sia il numero sia la capacità di sostenerlo in audit. Aggravanti: dipendenza dalle persone. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, regole e perimetri di calcolo, lineage e controlli e workflow e automazioni.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_medio_alto_medio": { diagnosi: "consolidamento privo di un linguaggio comune", copyApp: "Il quadro indica consolidamento privo di un linguaggio comune: riunire i dati non garantisce risultati confrontabili perché fonti e criteri possono descrivere realtà differenti. Aggravanti: dipendenza dalle persone e verifiche tardive. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, regole e perimetri di calcolo, workflow e automazioni e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_medio_alto_basso": { diagnosi: "consolidamento privo di un linguaggio comune", copyApp: "Il quadro indica consolidamento privo di un linguaggio comune: riunire i dati non garantisce risultati confrontabili perché fonti e criteri possono descrivere realtà differenti. Aggravanti: dipendenza dalle persone. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, regole e perimetri di calcolo e workflow e automazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_medio_medio_alto": { diagnosi: "lineage del dato incompleto", copyApp: "Il quadro indica lineage del dato incompleto: la distanza tra fonte ed evidenza finale rende costoso dimostrare come il dato sia stato costruito. Aggravanti: dipendenza dalle persone e comparabilità instabile. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, lineage e controlli, workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_medio_medio_medio": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. Aggravanti: dipendenza dalle persone, comparabilità instabile e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_medio_medio_basso": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. Aggravanti: dipendenza dalle persone e comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_medio_basso_alto": { diagnosi: "lineage del dato incompleto", copyApp: "Il quadro indica lineage del dato incompleto: la distanza tra fonte ed evidenza finale rende costoso dimostrare come il dato sia stato costruito. Aggravanti: dipendenza dalle persone. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, lineage e controlli e workflow e automazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_medio_basso_medio": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. Aggravanti: dipendenza dalle persone e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, workflow e automazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_medio_basso_basso": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. Aggravanti: dipendenza dalle persone. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni e workflow e automazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "alto_basso_alto_alto": { diagnosi: "fondazione del reporting non difendibile", copyApp: "Il quadro indica fondazione del reporting non difendibile: la combinazione di fonti disperse, criteri variabili e prove tardive indebolisce sia il numero sia la capacità di sostenerlo in audit. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su fonti e integrazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "alto_basso_alto_medio": { diagnosi: "consolidamento privo di un linguaggio comune", copyApp: "Il quadro indica consolidamento privo di un linguaggio comune: riunire i dati non garantisce risultati confrontabili perché fonti e criteri possono descrivere realtà differenti. Aggravanti: verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_basso_alto_basso": { diagnosi: "consolidamento privo di un linguaggio comune", copyApp: "Il quadro indica consolidamento privo di un linguaggio comune: riunire i dati non garantisce risultati confrontabili perché fonti e criteri possono descrivere realtà differenti. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_basso_medio_alto": { diagnosi: "lineage del dato incompleto", copyApp: "Il quadro indica lineage del dato incompleto: la distanza tra fonte ed evidenza finale rende costoso dimostrare come il dato sia stato costruito. Aggravanti: comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, lineage e controlli e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_basso_medio_medio": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. Aggravanti: comparabilità instabile e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_basso_medio_basso": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. Aggravanti: comparabilità instabile. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni e regole e perimetri di calcolo.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "alto_basso_basso_alto": { diagnosi: "lineage del dato incompleto", copyApp: "Il quadro indica lineage del dato incompleto: la distanza tra fonte ed evidenza finale rende costoso dimostrare come il dato sia stato costruito. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "alto_basso_basso_medio": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. Aggravanti: verifiche tardive. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "alto_basso_basso_basso": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_alto_alto_alto": { diagnosi: "controllo a posteriori del processo ESG", copyApp: "Il quadro indica controllo a posteriori del processo ESG: gli errori generati da attività manuali e regole locali emergono tardi, quando correggerli richiede rilavorazioni e nuove approvazioni. Aggravanti: riconciliazioni complesse. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su workflow e automazioni, regole e perimetri di calcolo, lineage e controlli e fonti e integrazioni.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "medio_alto_alto_medio": { diagnosi: "processo governato dall'interpretazione locale", copyApp: "Il quadro indica processo governato dall'interpretazione locale: attività manuali e criteri non uniformi trasferiscono la coerenza del reporting dalla piattaforma alle singole persone. Aggravanti: riconciliazioni complesse e verifiche tardive. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su workflow e automazioni, regole e perimetri di calcolo, fonti e integrazioni e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "medio_alto_alto_basso": { diagnosi: "processo governato dall'interpretazione locale", copyApp: "Il quadro indica processo governato dall'interpretazione locale: attività manuali e criteri non uniformi trasferiscono la coerenza del reporting dalla piattaforma alle singole persone. Aggravanti: riconciliazioni complesse. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, regole e perimetri di calcolo e fonti e integrazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_alto_medio_alto": { diagnosi: "circuito di controllo manuale", copyApp: "Il quadro indica circuito di controllo manuale: raccolta e verifica competono per le stesse risorse e trasformano ogni scadenza in una rincorsa alle evidenze. Aggravanti: riconciliazioni complesse e comparabilità instabile. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su workflow e automazioni, lineage e controlli, fonti e integrazioni e regole e perimetri di calcolo.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "medio_alto_medio_medio": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. Aggravanti: riconciliazioni complesse, comparabilità instabile e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, fonti e integrazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_alto_medio_basso": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. Aggravanti: riconciliazioni complesse e comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, fonti e integrazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_alto_basso_alto": { diagnosi: "circuito di controllo manuale", copyApp: "Il quadro indica circuito di controllo manuale: raccolta e verifica competono per le stesse risorse e trasformano ogni scadenza in una rincorsa alle evidenze. Aggravanti: riconciliazioni complesse. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, lineage e controlli e fonti e integrazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_alto_basso_medio": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. Aggravanti: riconciliazioni complesse e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, fonti e integrazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_alto_basso_basso": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. Aggravanti: riconciliazioni complesse. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su workflow e automazioni e fonti e integrazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_medio_alto_alto": { diagnosi: "governance debole nella dimostrabilità", copyApp: "Il quadro indica governance debole nella dimostrabilità: eccezioni e criteri variabili rendono difficile spiegare perché il dato sia corretto, comparabile e approvato. Aggravanti: riconciliazioni complesse e dipendenza dalle persone. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su regole e perimetri di calcolo, lineage e controlli, fonti e integrazioni e workflow e automazioni.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "medio_medio_alto_medio": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. Aggravanti: riconciliazioni complesse, dipendenza dalle persone e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su regole e perimetri di calcolo, fonti e integrazioni, workflow e automazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_medio_alto_basso": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. Aggravanti: riconciliazioni complesse e dipendenza dalle persone. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su regole e perimetri di calcolo, fonti e integrazioni e workflow e automazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_medio_medio_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. Aggravanti: riconciliazioni complesse, dipendenza dalle persone e comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su lineage e controlli, fonti e integrazioni, workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_medio_medio_medio": { diagnosi: "maturità ESG intermedia ma non ancora industrializzata", copyApp: "Il quadro indica maturità ESG intermedia ma non ancora industrializzata: nessun elemento è isolatamente fuori controllo, ma gli attriti distribuiti lungo l'intera catena possono trasformarsi in inefficienza e perdita di governo quando aumentano dati, sedi e obblighi. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su fonti e integrazioni, workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_medio_medio_basso": { diagnosi: "fabbrica del dato difficile da governare", copyApp: "Il quadro indica fabbrica del dato difficile da governare: fonti disperse, passaggi umani e criteri variabili possono produrre un consolidato formalmente completo ma sostanzialmente instabile. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni, workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_medio_basso_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. Aggravanti: riconciliazioni complesse e dipendenza dalle persone. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su lineage e controlli, fonti e integrazioni e workflow e automazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_medio_basso_medio": { diagnosi: "modello operativo opaco", copyApp: "Il quadro indica modello operativo opaco: il dato attraversa fonti e passaggi manuali senza una tracciabilità abbastanza rapida da sostenere verifiche e correzioni. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni, workflow e automazioni e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_medio_basso_basso": { diagnosi: "catena di raccolta frammentata e non scalabile", copyApp: "Il quadro indica catena di raccolta frammentata e non scalabile: la complessità cresce più rapidamente della capacità di acquisire e consolidare i dati in modo affidabile. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni e workflow e automazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_basso_alto_alto": { diagnosi: "governance debole nella dimostrabilità", copyApp: "Il quadro indica governance debole nella dimostrabilità: eccezioni e criteri variabili rendono difficile spiegare perché il dato sia corretto, comparabile e approvato. Aggravanti: riconciliazioni complesse. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su regole e perimetri di calcolo, lineage e controlli e fonti e integrazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_basso_alto_medio": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. Aggravanti: riconciliazioni complesse e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su regole e perimetri di calcolo, fonti e integrazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_basso_alto_basso": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. Aggravanti: riconciliazioni complesse. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su regole e perimetri di calcolo e fonti e integrazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_basso_medio_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. Aggravanti: riconciliazioni complesse e comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su lineage e controlli, fonti e integrazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "medio_basso_medio_medio": { diagnosi: "fondazione del reporting non difendibile", copyApp: "Il quadro indica fondazione del reporting non difendibile: la combinazione di fonti disperse, criteri variabili e prove tardive indebolisce sia il numero sia la capacità di sostenerlo in audit. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_basso_medio_basso": { diagnosi: "consolidamento privo di un linguaggio comune", copyApp: "Il quadro indica consolidamento privo di un linguaggio comune: riunire i dati non garantisce risultati confrontabili perché fonti e criteri possono descrivere realtà differenti. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni e regole e perimetri di calcolo.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_basso_basso_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. Aggravanti: riconciliazioni complesse. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su lineage e controlli e fonti e integrazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_basso_basso_medio": { diagnosi: "lineage del dato incompleto", copyApp: "Il quadro indica lineage del dato incompleto: la distanza tra fonte ed evidenza finale rende costoso dimostrare come il dato sia stato costruito. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su fonti e integrazioni e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "medio_basso_basso_basso": { diagnosi: "architettura del dato disconnessa", copyApp: "Il quadro indica architettura del dato disconnessa: la visione ESG dipende dalla capacità di ricomporre fonti disperse e può perdere copertura quando il perimetro cresce. L'esposizione è contenuta; serve una verifica preventiva della piattaforma ESG su fonti e integrazioni.", fitEnvizi: "fondazionale", raccomandazione: "Anche in un contesto semplice, IBM Envizi può offrire un'impostazione iniziale più ordinata, duratura e scalabile rispetto a Excel o a soluzioni di breve periodo." },
  "basso_alto_alto_alto": { diagnosi: "controllo a posteriori del processo ESG", copyApp: "Il quadro indica controllo a posteriori del processo ESG: gli errori generati da attività manuali e regole locali emergono tardi, quando correggerli richiede rilavorazioni e nuove approvazioni. L'esposizione è alta; serve un esame prioritario e approfondito della piattaforma ESG su workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strategico", raccomandazione: "IBM Envizi può sostenere una trasformazione strutturale del modello ESG, integrando dati, processi, regole e controlli in un impianto enterprise." },
  "basso_alto_alto_medio": { diagnosi: "processo governato dall'interpretazione locale", copyApp: "Il quadro indica processo governato dall'interpretazione locale: attività manuali e criteri non uniformi trasferiscono la coerenza del reporting dalla piattaforma alle singole persone. Aggravanti: verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_alto_alto_basso": { diagnosi: "processo governato dall'interpretazione locale", copyApp: "Il quadro indica processo governato dall'interpretazione locale: attività manuali e criteri non uniformi trasferiscono la coerenza del reporting dalla piattaforma alle singole persone. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_alto_medio_alto": { diagnosi: "circuito di controllo manuale", copyApp: "Il quadro indica circuito di controllo manuale: raccolta e verifica competono per le stesse risorse e trasformano ogni scadenza in una rincorsa alle evidenze. Aggravanti: comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, lineage e controlli e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_alto_medio_medio": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. Aggravanti: comparabilità instabile e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_alto_medio_basso": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. Aggravanti: comparabilità instabile. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_alto_basso_alto": { diagnosi: "circuito di controllo manuale", copyApp: "Il quadro indica circuito di controllo manuale: raccolta e verifica competono per le stesse risorse e trasformano ogni scadenza in una rincorsa alle evidenze. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su workflow e automazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_alto_basso_medio": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. Aggravanti: verifiche tardive. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su workflow e automazioni e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_alto_basso_basso": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su workflow e automazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_medio_alto_alto": { diagnosi: "governance debole nella dimostrabilità", copyApp: "Il quadro indica governance debole nella dimostrabilità: eccezioni e criteri variabili rendono difficile spiegare perché il dato sia corretto, comparabile e approvato. Aggravanti: dipendenza dalle persone. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su regole e perimetri di calcolo, lineage e controlli e workflow e automazioni.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_medio_alto_medio": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. Aggravanti: dipendenza dalle persone e verifiche tardive. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su regole e perimetri di calcolo, workflow e automazioni e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_medio_alto_basso": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. Aggravanti: dipendenza dalle persone. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su regole e perimetri di calcolo e workflow e automazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_medio_medio_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. Aggravanti: dipendenza dalle persone e comparabilità instabile. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su lineage e controlli, workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_medio_medio_medio": { diagnosi: "controllo a posteriori del processo ESG", copyApp: "Il quadro indica controllo a posteriori del processo ESG: gli errori generati da attività manuali e regole locali emergono tardi, quando correggerli richiede rilavorazioni e nuove approvazioni. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_medio_medio_basso": { diagnosi: "processo governato dall'interpretazione locale", copyApp: "Il quadro indica processo governato dall'interpretazione locale: attività manuali e criteri non uniformi trasferiscono la coerenza del reporting dalla piattaforma alle singole persone. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su workflow e automazioni e regole e perimetri di calcolo.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_medio_basso_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. Aggravanti: dipendenza dalle persone. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su lineage e controlli e workflow e automazioni.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_medio_basso_medio": { diagnosi: "circuito di controllo manuale", copyApp: "Il quadro indica circuito di controllo manuale: raccolta e verifica competono per le stesse risorse e trasformano ogni scadenza in una rincorsa alle evidenze. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su workflow e automazioni e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_medio_basso_basso": { diagnosi: "produzione del dato non scalabile", copyApp: "Il quadro indica produzione del dato non scalabile: l'operatività dipende dalle persone e assorbe capacità che dovrebbe essere dedicata al controllo e all'analisi. L'esposizione è contenuta; serve una verifica preventiva della piattaforma ESG su workflow e automazioni.", fitEnvizi: "fondazionale", raccomandazione: "Anche in un contesto semplice, IBM Envizi può offrire un'impostazione iniziale più ordinata, duratura e scalabile rispetto a Excel o a soluzioni di breve periodo." },
  "basso_basso_alto_alto": { diagnosi: "governance debole nella dimostrabilità", copyApp: "Il quadro indica governance debole nella dimostrabilità: eccezioni e criteri variabili rendono difficile spiegare perché il dato sia corretto, comparabile e approvato. L'esposizione è rilevante; serve un esame mirato della piattaforma ESG su regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "strutturale", raccomandazione: "IBM Envizi può consolidare il modello operativo ESG, riducendo frammentazione e rilavorazioni e creando una base comune per reporting e assurance." },
  "basso_basso_alto_medio": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. Aggravanti: verifiche tardive. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_basso_alto_basso": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su regole e perimetri di calcolo.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_basso_medio_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. Aggravanti: comparabilità instabile. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su lineage e controlli e regole e perimetri di calcolo.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_basso_medio_medio": { diagnosi: "governance debole nella dimostrabilità", copyApp: "Il quadro indica governance debole nella dimostrabilità: eccezioni e criteri variabili rendono difficile spiegare perché il dato sia corretto, comparabile e approvato. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_basso_medio_basso": { diagnosi: "governance semantica insufficiente", copyApp: "Il quadro indica governance semantica insufficiente: lo stesso indicatore può assumere significati diversi e rendere fragile il confronto tra sedi, periodi e perimetri. L'esposizione è contenuta; serve una verifica preventiva della piattaforma ESG su regole e perimetri di calcolo.", fitEnvizi: "fondazionale", raccomandazione: "Anche in un contesto semplice, IBM Envizi può offrire un'impostazione iniziale più ordinata, duratura e scalabile rispetto a Excel o a soluzioni di breve periodo." },
  "basso_basso_basso_alto": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. L'esposizione è moderata; serve una verifica strutturata della piattaforma ESG su lineage e controlli.", fitEnvizi: "evolutivo", raccomandazione: "IBM Envizi può accompagnare un'evoluzione graduale, sostituendo processi fragili o temporanei con workflow, regole e controlli più stabili e scalabili." },
  "basso_basso_basso_medio": { diagnosi: "assurance non pronta alla verifica", copyApp: "Il quadro indica assurance non pronta alla verifica: la prova dell'origine e dell'approvazione del dato arriva con ritardo rispetto alle esigenze di controllo. L'esposizione è contenuta; serve una verifica preventiva della piattaforma ESG su lineage e controlli.", fitEnvizi: "fondazionale", raccomandazione: "Anche in un contesto semplice, IBM Envizi può offrire un'impostazione iniziale più ordinata, duratura e scalabile rispetto a Excel o a soluzioni di breve periodo." },
  "basso_basso_basso_basso": { diagnosi: "tenuta futura da validare", copyApp: "Il quadro indica tenuta futura da validare: l'assetto appare oggi sotto controllo, ma la sua solidità non è ancora dimostrata rispetto a crescita del perimetro, nuove metriche e maggiori richieste di assurance. L'esposizione è contenuta; serve una verifica preventiva della piattaforma ESG su fonti e integrazioni, workflow e automazioni, regole e perimetri di calcolo e lineage e controlli.", fitEnvizi: "fondazionale", raccomandazione: "Anche in un contesto semplice, IBM Envizi può offrire un'impostazione iniziale più ordinata, duratura e scalabile rispetto a Excel o a soluzioni di breve periodo." },
};

export function lookup4x4(ratings: ("alto"|"medio"|"basso")[]): MatrixEntry | null {
  const [b, c, d, e] = ratings;
  if (!b || !c || !d || !e) return null;
  const key = `${b}_${c}_${d}_${e}` as Key;
  return MATRIX[key] ?? null;
}
